In [1]:
print("hello world!")

hello world!


In [ ]:
print("learning numpy")
#numpy is a library having numerical python
#it is used for scientific computing and data analysis

learning numpy


In [5]:
from array import *
arr= array('i',map(int, input("Enter the elements of array separated by space: ").split()))
print("the elements of array are: ", arr)

the elements of array are:  array('i', [1, 2, 3, 4, 5, 65])


In [ ]:
import numpy as np
#normal arrays 
arr1 = np.array(list(map(int , input("enter the elements of numpy array:").split())))
for i in arr1:
    print(i, end=" ")
print()
print(type(arr1))

2 3 4 5 
<class 'numpy.ndarray'>


In [ ]:
#range function in numpy
arr2= np.arange(1,12,2)
print(arr2)
arr3=np.arange(10)
print(arr3)

[ 1  3  5  7  9 11]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
#zeros and ones in numpy
arr4=np.zeros(10)
print(arr4)
arr5=np.ones(10)
print(arr5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#multi-dimensional arrays